### ISSUE TITLE
Remove logs when make request

### ISSUE THREAD

**Issue by eltonlaice** [paymentsds/mpesa-php-sdk#7]
* Hostname api.sandbox.vm.co.mz was found in DNS cache * Trying 197.235.3.18... * TCP_NODELAY set * Connected to api.sandbox.vm.co.mz (197.235.3.18) port 18352 (#0) * ALPN, offering http/1.1 * successfully set certificate verify locations: * CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 * ALPN, server accepted to use http/1.1 * Server certificate: * subject: C=GB; L=Newbury; O=Vodafone Group Services Limited; CN=developer.mpesa.vm.co.mz * start date: Feb 18 00:00:00 2020 GMT * expire date: Feb 22 12:00:00 2022 GMT * subjectAltName: host "api.sandbox.vm.co.mz" matched cert's "api.sandbox.vm.co.mz" * issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA * SSL certificate verify ok. > POST /ipg/v1x/c2bPayment/singleStage/ HTTP/1.1 Host: api.sandbox.vm.co.mz:18352 User-Agent: MPesa-PHP Origin: * Content-Type: application/json Authorization: Bearer CVjfhVnBo8ex4L54+feAOvUeFotff2p8aSsV8S+aN2vQWVX68CfnMPYfA9hk5o19DYU9Oo+P/YctmSpkWZEOPbWi/s+VD0ikabl/wOUxsOUr1emGy9EAOYBn5NShfpZnkeZYhsm1nz9Qoc6S68P08GBv3YXwhyFLCJUcdT3dZ9CvugNr2tohri1q3auO82+3X3hiVmgKue6nSc1pST8TODYTZVLLjlpmHxZzrnrCBtLAWj73w8/79mWTkNiJuaVWQNWBLh6SIQQYJfBSSK0awA39z18QKOKGB+KEh/Zicma2RVSdCR41HtOxPhRCTVb9D2xCrGdqpXZ2gBioWOCdiAG8LoVk2LTI9ylqzqsGFXg+rxAvXTft+uXQCe1he+MvraWVMSX/tynSK6ntJNRHfeGg6niZaocrYmbJ7/AReeeOkIaDA1Qv0OlD6NJmyssLADSs2xZqkXJGuwnFuFUQ/zfOeUyOJw5iifiKSmTYgSyVEtgiHOPE4vjIRDLCJb4dZ7soslQdj6drV7gER1KYYeHvoNcwgChsMon1YERPG4i5bOI0vZyKB4SsfyC7B6Jur7pLVg0swWh6M7nAIjiy/8enS6wp0KKYM5sCkoGT8bJepyLu2TFd94TwxIIQuOjDgYcQ+Lx2CNKIgJ4KwOXXpxwBkoev0lPvHcKDHyZRXOw= Content-Length: 174 * upload completely sent off: 174 out of 174 bytes < HTTP/1.1 201 Created < Date: Wed, 12 Aug 2020 03:50:36 GMT < Content-Type: application/json < Content-Length: 221 < Connection: keep-alive < X-Frame-Options: SAMEORIGIN < X-Robots-Tag: none < X-Content-Type-Options: nosniff < X-XSS-Protection: 1; mode=block < Strict-Transport-Security: max-age=16005600; includeSubDomains < Access-Control-Allow-Origin: * < Server: Server < X-Frame-Options: SAMEORIGIN < X-Content-Type-Options: nosniff < X-XSS-Protection: 1; mode=block < * Connection #0 to host api.sandbox.vm.co.mz left intact

**Comment by hericogimo** [comment]
1. set **debug** as _false_ in the class [**src\Paymentsds\MPesa\Service.php** ](https://github.com/paymentsds/mpesa-php-sdk/blob/develop/src/Paymentsds/MPesa/Service.php) in function _performRequest($opcode, $intent)_ : 

```
$data = [
    'headers' => $headers,
    'debug' => false,
    'verify' => $this->config->verifySSL
];
```

2. Also in the construct function in [**src\Paymentsds\MPesa\Configuration.php**](https://github.com/paymentsds/mpesa-php-sdk/blob/develop/src/Paymentsds/MPesa/Configuration.php) : 

```
 $this->environment = Environment::fromURL(Environment::SANDBOX);
  $this->debugging = false;
  $this->verifySSL = true;
  $this->origin = '*';
  $this->userAgent = 'MPesa-PHP';
  $this->timeout = 0;
```
