### ISSUE TITLE
curl_setopt_array() exception when using SDK on windows

### ISSUE THREAD

**Issue by mauromauane** [paymentsds/mpesa-php-sdk#9]
Hi,
I am trying to use the SDK on windows, but I getting a Uncaught GuzzleHttp\Exception\RequestException after introducing PIN on mobile.
See the file in attack.

Can you please help? I think it only happen on windows

![PaymentDS](https://user-images.githubusercontent.com/10763752/95127669-a3b50c80-0758-11eb-8369-a86582d8c7a1.PNG)
![PymentDSLine72](https://user-images.githubusercontent.com/10763752/95127747-cba47000-0758-11eb-8d98-943d6eea2dd4.PNG)

**Comment by inkomomutane** [comment]
I have same problem on laravel 7.x

![recentt](https://user-images.githubusercontent.com/57417802/97289285-a97da980-184f-11eb-8e2c-33ef4173a31e.jpg)

**Comment by edsonmichaque** [comment]
@inkomomutane can you describe your setup?

**Comment by joseseie** [comment]
Infelizmente esse bug é frequente principalmente no windows. 😞

**Comment by edsonmichaque** [comment]
@joseseie pela investigação que fiz está relacionado com o cliente HTTP (Guzzle HTTP) que usamos, estou aqui a ponderar uma solução que consiste em remover a dependência em em relação ao Guzzle HTTP e passarmos a usar o cURL directamante

**Comment by edsonmichaque** [comment]
@mauromauane, @inkomomutane and @joseseie I think we've solved this issue. Can you guys test again and give feedback?
